services:

  admin_bot:
    container_name: "admin_bot"
    build: ./admin
    command: sh -c "python main.py"
    env_file:
      - .env
    depends_on:
      - postgresdb

  users_bot:
    container_name: "users_bot"
    build: ./users
    command: sh -c "python main.py"
    env_file:
      - .env
    depends_on:
      - postgresdb
      - admin_bot

  postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5434:5432

volumes:
  postgres_data: